export const MOCK: ISearchSnippet[] = [
  {
    title: 'Binary Diagnostic - Advent of Code 2021 Day 03',
    date: '2022-05-21',
    tags: ['ramda'],
    slug: 'adventofcode2021/binary-diagnostic',
    group: 'adventofcode2021',
    topic: 'javascript',
  },
  {
    title: 'Dive - Advent of Code 2021 Day 02',
    date: '2022-05-21',
    tags: ['ramda'],
    slug: 'adventofcode2021/dive',
    group: 'adventofcode2021',
    topic: 'javascript',
  },
  {
    title: 'Giant Squid - Advent of Code 2021 Day 04',
    date: '2022-05-23',
    tags: ['ramda'],
    slug: 'adventofcode2021/giant-squad',
    group: 'adventofcode2021',
    topic: 'javascript',
  },
  {
    title: 'Hydrothermal Venture - Advent of Code 2021 Day 05',
    date: '2022-05-23',
    tags: ['ramda'],
    slug: 'adventofcode2021/hydrothermal-venture',
    group: 'adventofcode2021',
    topic: 'javascript',
  },
  {
    title: 'Lanternfish - Advent of Code 2021 Day 06',
    date: '2022-05-23',
    tags: ['ramda'],
    slug: 'adventofcode2021/lanternfish',
    group: 'adventofcode2021',
    topic: 'javascript',
  },
  {
    title: 'Seven Segment Search - Advent of Code 2021 Day 08',
    date: '2022-05-24',
    tags: ['ramda'],
    slug: 'adventofcode2021/seven-segment-search',
    group: 'adventofcode2021',
    topic: 'javascript',
  },
  {
    title: 'Sonar Sweep - Advent of Code 2021 Day 01',
    date: '2022-05-21',
    tags: ['ramda'],
    slug: 'adventofcode2021/sonar-sweep',
    group: 'adventofcode2021',
    topic: 'javascript',
  },
  {
    title: 'The Treachery of Whales - Advent of Code 2021 Day 07',
    date: '2022-05-24',
    tags: ['ramda'],
    slug: 'adventofcode2021/whales-treachery',
    group: 'adventofcode2021',
    topic: 'javascript',
  },
  {
    title: 'Inject jQuery into web pages to enable scraping',
    date: '2020-01-22',
    tags: [],
    slug: 'jquery/inject',
    group: 'scraping',
    topic: 'javascript',
  },
  {
    title: 'Introduction to Elasticsearch',
    date: '2022-05-21',
    tags: [],
    slug: 'esdeepdive/intro',
    group: 'esdeepdive',
    topic: 'elasticsearch',
  },
  {
    title: 'Bubblesort - Algorithms Illuminated Vol 1',
    date: '2022-07-08',
    tags: ['sorting'],
    slug: 'illuminated01/bubblesort',
    group: 'illuminated01',
    topic: 'rust',
  },
  {
    title: 'Count Inversions - Algorithms Illuminated Vol 1',
    date: '2022-07-08',
    tags: ['divideconquer'],
    slug: 'illuminated01/countinversions',
    group: 'illuminated01',
    topic: 'rust',
  },
  {
    title: 'Index Match - Algorithms Illuminated Vol 1',
    date: '2022-07-08',
    tags: ['divideconquer'],
    slug: 'illuminated01/indexmatch',
    group: 'illuminated01',
    topic: 'rust',
  },
  {
    title: 'Binary Diagnostic - Advent of Code 2021 Day 03',
    date: '2022-05-21',
    tags: ['divideconquer'],
    slug: 'illuminated01/inversions',
    group: 'illuminated01',
    topic: 'rust',
  },
  {
    title: 'Mergesort - Algorithms Illuminated Vol 1',
    date: '2022-07-08',
    tags: ['divideconquer', 'sorting'],
    slug: 'illuminated01/mergesort',
    group: 'illuminated01',
    topic: 'rust',
  },
  {
    title: 'Quicksort - Algorithms Illuminated Vol 1',
    date: '2022-07-08',
    tags: ['divideconquer', 'sorting'],
    slug: 'illuminated01/quicksort',
    group: 'illuminated01',
    topic: 'rust',
  },
  {
    title: 'Selection sort - Algorithms Illuminated Vol 1',
    date: '2022-07-08',
    tags: ['sorting'],
    slug: 'illuminated01/selectionsort',
    group: 'illuminated01',
    topic: 'rust',
  },
  {
    title: 'Unimodal Array - Algorithms Illuminated Vol 1',
    date: '2022-07-08',
    tags: ['divideconquer'],
    slug: 'illuminated01/unimodal',
    group: 'illuminated01',
    topic: 'rust',
  },
  {
    title: 'Merging JSON files into CSV format',
    date: '2022-02-20',
    tags: [],
    slug: 'streams/converttocsv',
    group: 'streams',
    topic: 'nodejs',
  },
  {
    title: 'Merging JSON files into NDJSON format',
    date: '2022-03-05',
    tags: [],
    slug: 'streams/merge',
    group: 'streams',
    topic: 'nodejs',
  },
  {
    title: '#25 Access deeper parts of objects and arrays',
    date: '2022-07-11',
    tags: ['tricks'],
    slug: 'typescripttips/access-types-with-unions',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: '#18 Use assertion functions inside classes',
    date: '2022-04-06',
    tags: ['tricks'],
    slug: 'typescripttips/assertion-functions',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title:
      '#20 Assign local variables to default generic slots to dry up your code and improve performance',
    date: '2022-04-11',
    tags: ['tricks'],
    slug: 'typescripttips/assigning-local-variables-generic',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: '#23 Ensure that all call sites must be given value',
    date: '2022-06-07',
    tags: ['tricks'],
    slug: 'typescripttips/call-sites',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: '#22 Understand how TypeScript infers literal types',
    date: '2022-05-16',
    tags: ['tricks'],
    slug: 'typescripttips/const-variables',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title:
      "#9 Create a 'key remover' function which can process any generic object",
    date: '2022-03-16',
    tags: ['tricks'],
    slug: 'typescripttips/currying-generics',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: '#3 Decode URL search params at the type level',
    date: '2022-03-02',
    tags: ['tricks'],
    slug: 'typescripttips/decoding-search-params',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: '#11 Use deep partials to help with mocking an entity',
    date: '2022-03-21',
    tags: ['tricks'],
    slug: 'typescripttips/deep-partials',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: '#1 Derive a union type from an object',
    date: '2022-02-25',
    tags: ['tricks'],
    slug: 'typescripttips/derive-union-types',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: '#17 Map over a union type',
    date: '2022-04-06',
    tags: ['tricks'],
    slug: 'typescripttips/distributive-conditional-types',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: '#8 Use generics in React to make dynamic and flexible components',
    date: '2022-03-14',
    tags: ['tricks'],
    slug: 'typescripttips/dynamic-components',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: '#4 Use function overloads and generics to type a compose function',
    date: '2022-03-04',
    tags: ['tricks'],
    slug: 'typescripttips/dynamic-type-signatures',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: '#10 Throw detailed error messages for type checks',
    date: '2022-03-18',
    tags: ['tricks'],
    slug: 'typescripttips/error-type-checks',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title:
      "#6 Write your own 'PropsFrom' helper to extract props from any React component",
    date: '2022-03-09',
    tags: ['tricks'],
    slug: 'typescripttips/extract-props',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title:
      '#15 Use generics to dynamically specify the number, and type, of arguments to functions',
    date: '2022-04-01',
    tags: ['tricks'],
    slug: 'typescripttips/generics-arguments-functions',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: "#5 Use 'extends' keyword to narrow the value of a generic",
    date: '2022-03-07',
    tags: ['tricks'],
    slug: 'typescripttips/generics-autocomplete',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: "#14 Use 'declare global' to allow types to cross module boundaries",
    date: '2022-03-30',
    tags: ['tricks'],
    slug: 'typescripttips/globals-typescript',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: '#12 Create autocomplete helper which allows for arbitrary values',
    date: '2022-03-23',
    tags: ['tricks'],
    slug: 'typescripttips/loose-autocomplete',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: '#13 Turn a module into a type',
    date: '2022-03-28',
    tags: ['tricks'],
    slug: 'typescripttips/module-to-type',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title:
      "#16 Make accessing objects safer by enabling 'noUncheckedIndexedAccess' in tsconfig",
    date: '2022-04-04',
    tags: ['tricks'],
    slug: 'typescripttips/nounchecked-indexed-access',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: '#21 Publishing TypeScript package up to NPM',
    date: '2022-05-13',
    tags: ['tricks'],
    slug: 'typescripttips/preconstruct',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: '#24 Typescript Satisfies Operator',
    date: '2022-06-14',
    tags: ['tricks'],
    slug: 'typescripttips/satisfies',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: '#2 Transform Union into Another',
    date: '2022-02-28',
    tags: ['tricks'],
    slug: 'typescripttips/transform-union',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title:
      "#7 Create your own 'objectKeys' function using generics and the 'keyof' operator",
    date: '2022-03-11',
    tags: ['tricks'],
    slug: 'typescripttips/type-safe-object-keys',
    group: 'tips',
    topic: 'typescript',
  },
  {
    title: '#19 Know when to use generics',
    date: '2022-04-11',
    tags: ['tricks'],
    slug: 'typescripttips/when-to-use-generics',
    group: 'tips',
    topic: 'typescript',
  },
]
